# Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np # linear algebra
import pandas as pd # data processing
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
dataset = pd.read_csv("advertising.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X[:10]

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2]])

In [4]:
y[:10]

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6])

# Scaling the dataset

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [6]:
X[:10]

array([[ 0.96985227,  0.98152247,  1.77894547],
       [-1.19737623,  1.08280781,  0.66957876],
       [-1.51615499,  1.52846331,  1.78354865],
       [ 0.05204968,  1.21785493,  1.28640506],
       [ 0.3941822 , -0.84161366,  1.28180188],
       [-1.61540845,  1.73103399,  2.04592999],
       [-1.04557682,  0.64390467, -0.32470841],
       [-0.31343659, -0.24740632, -0.87248699],
       [-1.61657614, -1.42906863, -1.36042422],
       [ 0.61604287, -1.39530685, -0.43058158]])

# Splitting the dataset

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [8]:
X_train[:10]

array([[-0.43487612, -0.60528119,  0.05275246],
       [ 0.96284614,  0.61014289,  2.00910454],
       [ 1.24659427, -0.13261627, -0.02550162],
       [ 0.4420574 , -0.15287334, -0.39375613],
       [-1.19504085,  0.17123975, -0.45820067],
       [-0.98952781, -0.72007125, -0.56407384],
       [ 1.70316018,  0.34004865,  0.58211831],
       [ 0.29726411, -0.34869167,  0.00672064],
       [ 0.64757044, -0.06509271,  0.04814928],
       [-1.63175608,  0.32654394,  0.49926105]])

In [9]:
X_test[:10]

array([[-0.90895735, -0.18663512, -0.56407384],
       [-1.1331534 , -0.78759481, -0.55947066],
       [-0.66140754, -1.55061104, -0.33851796],
       [ 1.66579418,  1.28537849,  0.95037282],
       [ 0.27040729, -1.04418434,  0.21386381],
       [-1.06075676, -1.18598381, -0.03931117],
       [-1.61540845,  1.73103399,  2.04592999],
       [ 1.08662104, -1.07794612, -1.00597925],
       [-1.4390876 ,  0.79920886,  1.62704048],
       [ 0.59035374,  0.00243085, -0.75280428]])

In [10]:
y_train[:10]

array([12.4, 19.7, 17.6, 20.5, 10.1,  9.7, 21.4, 16.4, 16.6,  5.5])

In [11]:
y_test[:10]

array([11.3,  8.4, 12. , 25.4, 16.7,  8.7,  7.2, 18.2,  9.2, 16.6])

# Training the multiple linear regression model

In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

# Making prediction

In [13]:
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[10.69034418 11.3       ]
 [ 8.68132435  8.4       ]
 [ 9.59290052 12.        ]
 [24.88241319 25.4       ]
 [14.68606352 16.7       ]
 [ 8.36077587  8.7       ]
 [10.5898131   7.2       ]
 [18.36838345 18.2       ]
 [ 9.87359003  9.2       ]
 [17.86306812 16.6       ]
 [23.40835973 24.2       ]
 [10.69153461 10.6       ]
 [13.38610616 15.5       ]
 [17.09651474 20.6       ]
 [11.7596204  11.8       ]
 [13.31736836 13.2       ]
 [21.13410725 17.4       ]
 [ 9.13820326  1.6       ]
 [14.17420598 14.7       ]
 [18.85121771 17.        ]
 [24.84655353 26.2       ]
 [12.43749806 10.3       ]
 [16.57128353 16.1       ]
 [13.79857232 12.9       ]
 [ 7.80827038  8.1       ]
 [15.12861077 15.2       ]
 [14.68386733 17.6       ]
 [20.66548775 22.6       ]
 [16.96644118 16.6       ]
 [ 8.90614184  8.5       ]
 [12.38904935 12.5       ]
 [20.8124535  23.7       ]
 [21.26609738 16.1       ]
 [21.84309375 21.8       ]
 [ 7.18768267  5.6       ]
 [ 7.06323314  6.7       ]
 [ 9.23756125  9.7       ]
 

# Testing accuracy

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8718069474344206